version: '3.8'

services:
  web:
    build:
      context: ./go
      dockerfile: Go.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./go:/usr/src/app
    command: go run main.go
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports: 
      - "5432:5432"
    restart: always
    volumes: 
      - ./postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=DEV_HUNTER
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
